on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn install -DskipTests -am -pl flink-connectors/flink-connector-hive
    - name: Test
      run: mvn test -pl flink-connectors/flink-connector-hive -Dtest=org.apache.flink.connectors.hive.HiveRunnerITCase#testWriteComplexType
    - name: Test with NonDex
      run: mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -pl flink-connectors/flink-connector-hive -DnondexRuns=10 -Dtest=org.apache.flink.connectors.hive.HiveRunnerITCase.testWriteComplexType
